### PR TITLE
fix 1098

### LINKED ISSUE #1098: Click the search results on the left, the right page cannot be located
#### Steps to reproduce
show this in stackoverflow
https://stackoverflow.com/questions/60945607/docsify-click-the-search-results-on-the-left-the-right-page-cannot-be-located

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[Edit 307qqv236](https://codesandbox.io/s/307qqv236)

### PR DESCRIPTION
**Pull request by sy-records**
**Summary**

fix #1098

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

---

* [ ] DO NOT include files inside `lib` directory.

### CODE REVIEW

File: src/plugins/search/component.js [hunk 1]
```diff
@@ -174,7 +174,9 @@ function bindEvents() {
   Docsify.dom.on(
     $search,
     'click',
-    e => e.target.tagName !== 'A' && e.stopPropagation()
+    e =>
+      ['A', 'H2', 'P', 'EM'].indexOf(e.target.tagName) === -1 &&
```
Comment (anikethsaha) [inline src/plugins/search/component.js:178]: what about other tags ?

Comment (sy-records) [reply src/plugins/search/component.js:178]: Are there any others? All i see is this.
image

Comment (anikethsaha) [reply src/plugins/search/component.js:178]: ahh, yeah I checked the code, it seems these are enough. we can add them later if we missed something 👍

Comment (trusktr) [reply src/plugins/search/component.js:178]: What about using `preventDefault` instead of `stopPropagation`? It would make the event handleable by high up code.

Also, maybe we can make this more generic and not maintain a list of specific DOM nodes, so that code won't break if we update markup structure.

How about something like 

```js
// select any anchor and anything inside the anchors
const linkContent = $search.find('a *')

// ...

    e =>
      !$(e.target).is(linkContent) && e.preventDefault()?
```

?

Comment (trusktr) [reply src/plugins/search/component.js:178]: In general I think we should improve output so Docsify content is clear, and we can rely on something like

```js
const linkContent = $search.find('.docsify-link *')
```

I had started doing that in my one messy PR. I will split it up soon. But feel free to pluck changes if I'm too slow!

Comment (trusktr) [reply src/plugins/search/component.js:178]: Oh, I think `stopPropagation` is to prevent the menu from closing in another event handler, isn't it? Nevermind preventDefault then (for now).

In that case, it may be cleaner to consolidate that other code with this code, so that the intent is clear, but that's a bigger task.

Comment (stepozer) [reply src/plugins/search/component.js:178]: Today I also found this code :) I have question, what if we totally delete this section? 
```

// Prevent to Fold sidebar   -   what does it mean???
    Docsify.dom.on(
      $search,
      'click',
      function (e) { return e.target.tagName !== 'A' && e.stopPropagation(); }
    );
```

I deleted it and nothing happens. What bug this code fix? Do you know? I think better will delete this code instead try determine which tag type user click.

Comment (sy-records) [reply src/plugins/search/component.js:178]: > 今天，我也找到了这段代码：)我有一个问题，如果我们完全删除此部分该怎么办？
> 
> ```
> 
> // Prevent to Fold sidebar   -   what does it mean???
>     Docsify.dom.on(
>       $search,
>       'click',
>       function (e) { return e.target.tagName !== 'A' && e.stopPropagation(); }
>     );
> ```
> 
> 我删除了它，没有任何反应。此代码修复了哪些错误？你知道吗？我认为最好删除此代码，而不是尝试确定用户单击哪种标记类型。

When searching on the mobile end, the sidebar is collapsed when you click the INPUT box, making it impossible to search.

Comment (sy-records) [reply src/plugins/search/component.js:178]: > Today I also found this code :) I have question, what if we totally delete this section?
> 
> ```
> 
> // Prevent to Fold sidebar   -   what does it mean???
>     Docsify.dom.on(
>       $search,
>       'click',
>       function (e) { return e.target.tagName !== 'A' && e.stopPropagation(); }
>     );
> ```
> 
> I deleted it and nothing happens. What bug this code fix? Do you know? I think better will delete this code instead try determine which tag type user click.

When searching on the mobile end, the sidebar is collapsed when you click the INPUT box, making it impossible to search.

Comment (sy-records) [reply src/plugins/search/component.js:178]: @trusktr Hi, I think it's okay to modify it this way for now, and there should be no other DOM.
If it's going to be modified, it should be in v5, and the next release shouldn't be v5.

Comment (stepozer) [reply src/plugins/search/component.js:178]: In this case I suggest:

1. Write commend that describe why this code needed. For example:
```
When searching on the mobile end, the sidebar is collapsed when you click the INPUT box, making it impossible to search.
```

2. I suggest try to search closest parent link `A` instead all of this tags. Maybe it will be more correct? 

What do you think about it?

Comment (sy-records) [reply src/plugins/search/component.js:185]: @stefek99 As I said in https://github.com/docsifyjs/docsify/pull/1175#discussion_r424240260, there are only so many DOMs... 
if there are other more excellent way you can modify this PR, thanks!

Comment (sy-records) [reply src/plugins/search/component.js:185]: @stepozer Thanks to the first point of suggestion, which has been revised. 

On the second point, as I said in https://github.com/docsifyjs/docsify/pull/1175#discussion_r424240260, there are only so many DOMs... 

if there are other more excellent way you can modify this PR, thanks!

Comment (stepozer) [reply src/plugins/search/component.js:185]: @sy-records as I suggested you can:

1. stopPropagation if current element == `A` tag
2. stopPropagation if current element has parent == `A` tag

Because how I understand all this tags always wrapped in `A`. What do you think?

Comment (sy-records) [reply src/plugins/search/component.js:185]: `stopPropagation if current element == A tag` This doesn't seem right. 🤔

Comment (stepozer) [reply src/plugins/search/component.js:185]: For pure JS exists equivalent https://stackoverflow.com/questions/38469830/what-is-the-pure-javascript-equivalent-of-jquerys-parents-method

Comment (stepozer) [reply src/plugins/search/component.js:185]: > `stopPropagation if current element == A tag` This doesn't seem right.

Sorry, I mean `!==`. Right now you has logic:

if  e.target.tagName !== 'A' then stopPropagation. But in your tag `A` exists other tags, so you need check parent for this tag:

stopPropagation if current element !== A AND current element has NO parents with A tag.

Comment (stepozer) [reply src/plugins/search/component.js:185]: I tried write code, I think it will be something like this:

```
function getParentByTag(e, parentTag) {
    for (var p = e && e.parentElement; p; p = p.parentElement) {
      if (p && p.tagName == parentTag) {
        return p;
      }
    }
    return null;
  }

  function elementIsLinkOrHasLinkOnParents(element) {
    var parenLink = getParentByTag(element, 'A')
    return element.tagName === 'A' || parenLink != null;
  }

// Prevent to Fold sidebar
Docsify.dom.on(
  $search,
  'click',
  function (e) { return !elementIsLinkOrHasLinkOnParents(e.target) && e.stopPropagation(); }
);
```

Sorry, I am back-end developer :)

Comment (stepozer) [reply src/plugins/search/component.js:185]: I tested on mobile, seems to be working...

Comment (sy-records) [reply src/plugins/search/component.js:185]: It's a little complicated... Let's keep it simple. 😥

Comment (stepozer) [reply src/plugins/search/component.js:185]: I will create separated PR for this :) I think it will be more right way

Comment (sy-records) [reply src/plugins/search/component.js:185]: Sure, feel free to submit a PR. 👍🏻

Comment (stepozer) [reply src/plugins/search/component.js:185]: Will wait until your PR will be merged

**Comment by anikethsaha** [comment]
cc @trusktr @Koooooo-7
