### PR TITLE
fix: sidebar title error

### LINKED ISSUE #1359: The feature "Set Page Titles from Sidebar Selection" does not seem to be working
## Bug Report
The document of docsify says
> A page's title tag is generated from the selected sidebar item name. For better SEO, you can customize the title by specifying a string after the filename.
> ```markdown
> 
> * [Home](/)
> * [Guide](guide.md "The greatest guide in the world")
> ```

But when I do it, the  page's title is still "Guide"  rather than "The greatest guide in the world".
#### Steps to reproduce
Normally add files,nothing special.

#### What is current behaviour
The title of page is from sidebar item name.

#### What is the expected behaviour
customized title can work.

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Ubuntu 16.04.7
- Node.js version: 14.7.0
- npm/yarn version: 6.14.7
- Browser version: Firefox v79.0
- Docsify version: 4.11.6
- Docsify plugins: 字数统计（docsify-count），scrollToTop

#### Please create a reproducible sandbox 

[Edit share-docsify-qnsk9](https://codesandbox.io/s/share-docsify-qnsk9)

### PR DESCRIPTION
**Pull request by sy-records**
**Summary**

fix #1359

Bugs caused by #1286

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Repo settings
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

### CODE REVIEW

**Review by anikethsaha — APPROVED** [review]

File: src/core/event/sidebar.js [hunk 1]
```diff
@@ -86,7 +86,7 @@ export function getAndActive(router, el, isParent, autoTitle) {
       const href = a.getAttribute('href');
       const node = isParent ? a.parentNode : a;
 
-      a.title = a.innerText;
+      a.title = a.title || a.innerText;
```
Comment (anikethsaha) [inline src/core/event/sidebar.js:89]:
```suggestion
      a.title = a.innerText || a.title;
```

should it be like this ?

**Review by anikethsaha — CHANGES_REQUESTED** [review]

File: src/core/event/sidebar.js (hunk 1 above)
Comment (sy-records) [reply src/core/event/sidebar.js:89]: no, In this case, there's already a title, so we don't need to set it up again.

```markdown
<!-- docs/_sidebar.md -->
* [Home](/)
* [Guide](guide.md "The greatest guide in the world")
```

Comment (anikethsaha) [reply src/core/event/sidebar.js:89]: cool

**Review by anikethsaha — DISMISSED** [review]

**Review by anikethsaha — APPROVED** [review]

**Review by Koooooo-7 — APPROVED** [review]
