### PR TITLE
Fix #1136 and #1127

### LINKED ISSUE #1136: click left sidebar, then refresh the page, lost the sync scroll.
#### Steps to reproduce

1. open a page like https://docsify.js.org/#/configuration

2. click a sub-sidebar link (the toc of current document), or click a heading in the main content

3. using F5, refresh the current page

#### What is current behaviour

the page lost sync scroll. 
when you scroll the main page, the sidebar could not sync scroll.

#### What is the expected behaviour

 the sidebar sync scroll always.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[Edit 307qqv236](https://codesandbox.io/s/307qqv236)

### PR DESCRIPTION
**Pull request by vagra**
**Summary**
Fix #1136 and #1127

**What kind of change does this PR introduce?** (check at least one)

- [x ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x ] Chrome
- [x ] Firefox
- [x ] Safari
- [x ] Edge
- [x ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

---

* [ ] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by vagra** [comment]
Review required

File: src/core/router/util.js [hunk 1]
```diff
@@ -44,6 +44,10 @@ export const isAbsolutePath = cached(path => {
   return /(:|(\/{2}))/g.test(path);
 });
 
+export const removeParams = cached(path => {
+  return path.split(/[?#]/)[0];
```
Comment (Koooooo-7) [inline src/core/router/util.js:48]: could give more details about why you wanna just keep the base path?

Comment (anikethsaha) [reply src/core/router/util.js:48]: Yes, I agree. can your describe your changes.

Comment (vagra) [reply src/core/router/util.js:48]: this code fix the bug #1136:



1. open a page like 'https://docsify.js.org/#/configuration'

2. click a sub-sidebar link, or click a heading in the main conten, like 'markdown', the url in browser address changes to: 'https://docsify.js.org/#/configuration?id=markdown'

3. using F5 refresh this page, or open a new tab as address 'https://docsify.js.org/#/configuration?id=markdown' in brower.

4. now, sidebar and main body lost sync scroll.

5. because in the function highlight(path)  in scroll.js, does not handle the `id` in `path`;
so , it can't find the corresponding link in sidebar;
so, sidebar and main body does not sync scroll.

6. so, I using this removeParams function, extract base url of the page from the hole url.
```
input: https://docsify.js.org/#/configuration?id=markdown
or: https://docsify.js.org/#/configuration#markdown

output: https://docsify.js.org/#/configuration
```

7. then, docsify can find the corresponding link from urls with `id` param, so, it can sync scroll always.

Comment (anikethsaha) [reply src/core/router/util.js:48]: I didnt test the change locally (lack of time, sorry ! )
can you confirm that with this change, will the `id` in the sidebar be highlighted after refresh?

Comment (vagra) [reply src/core/router/util.js:48]: yes. I tested this bugfix at firefox/chrome/edge/ie , and place a temp site at https://kepan.org/bugfix
when you click a sidebar item or main body heading, then refresh the browser, or using a url with `id` param like https://kepan.org/bugfix/#/configuration?id=name , the sidebar item always highlighted, and sync scroll.
