### PR TITLE
fix~issues 1110

### LINKED ISSUE #1110: Cannot read property 'contains' of undefined
#### Steps to reproduce
When clicking the result switching page in the left search box, an error will be reported
image
Uncaught TypeError: Cannot read property 'contains' of undefined
    at HTMLElement.<anonymous> (docsify.min.js:1)

After query, the source code needs to be modified
Modify 539 lines of source code and add a layer of judgment

image

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[Edit 307qqv236](https://codesandbox.io/s/307qqv236)

### PR DESCRIPTION
**Pull request by CHU295**
**Summary**
fix #1110

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

---

* [ ] DO NOT include files inside `lib` directory.

### CODE REVIEW

File: src/plugins/search/component.js [hunk 1]
```diff
@@ -171,11 +171,11 @@ function bindEvents() {
...
-  Docsify.dom.on(
-    $search,
-    'click',
-    e => e.target.tagName !== 'A' && e.stopPropagation()
-  );
+//   Docsify.dom.on(
+//     $search,
+//     'click',
+//     e => e.target.tagName !== 'A' && e.stopPropagation()
+//   );
```
Comment (anikethsaha) [inline src/plugins/search/component.js:178]: Why this :?

Comment (CHU295) [reply src/plugins/search/component.js:178]: fix this bug
https://github.com/docsifyjs/docsify/issues/1098

 in most cases, the element that triggers the click event is not tag A .
At this time, stopPropagation event causing click the search results on the left, the right page cannot be located.
In your source code, the location is triggered by listening to the click event

**Comment by sy-records** [comment]
image
Did this change the file name?

File: src/plugins/search/component.js [hunk 2]
```diff
@@ -171,11 +171,6 @@ function bindEvents() {
 
   let timeId;
   // Prevent to Fold sidebar
-  Docsify.dom.on(
-    $search,
-    'click',
-    e => e.target.tagName !== 'A' && e.stopPropagation()
-  );
```
Comment (anikethsaha) [inline src/plugins/search/component.js:178]: can you comment this instead of delete. also add why this is being commented.
use block comments (`/** ... */`)

Comment (sy-records) [reply src/plugins/search/component.js:178]: He said here https://github.com/docsifyjs/docsify/pull/1111#discussion_r408640781

Comment (anikethsaha) [reply src/plugins/search/component.js:178]: yeah, this is just for future reference. we can add a link to this PR instead of details.

Comment (sy-records) [reply src/plugins/search/component.js:178]: Well, I tested the mobile end and he'll affect the sidebar.

Comment (anikethsaha) [reply src/plugins/search/component.js:178]: can you share the details in a separate review so that he can take a look

File: src/plugins/search/component.js [hunk 3]
```diff
@@ -171,11 +171,6 @@ function bindEvents() {
 
   let timeId;
   // Prevent to Fold sidebar
-  Docsify.dom.on(
```
Comment (sy-records) [inline src/plugins/search/component.js:174]: After deletion, the sidebar will be collapsed when using search on the mobile end, making search unavailable.

File: src/plugins/search/component.js (hunk 1 above)
Comment (trusktr) [reply src/plugins/search/component.js]: Oh I see. I wonder why that was there though. Why did it wasn't too prevent clicks on non-anchor tags?

**Comment by sy-records** [comment]
@docsifyjs/reviewers  We can remove the modified component.js and use this PR to fix #1110.

**Comment by anikethsaha** [comment]
cc @CHU295 can you change the PR to `fix #1110`

**Comment by sy-records** [comment]
@anikethsaha I modified it for him.
