### PR TITLE
fix #970, updated the insertion of embedded tokens for async returns

### LINKED ISSUE #970: Multiple embed files not loaded correctly
#### Steps to reproduce
Embedding multiple bullet list .md files, for example:

**Sources in _test-embedding.md**
```
## A
- `1`

[filename](./media/a.md ':include')

## B
- `2`

[filename](./media/b.md ':include')

## C
- `3`

[filename](./media/c.md ':include')
```

**Sources in media/a.md**
```
- `A1` AAA
- `A2` AAA
- `A3` AAA
```

**Sources in media/b.md**
```
- `A1` AAA
- `A2` AAA
- `A3` AAA
```

**Sources in media/c.md**
```
- `A1` AAA
- `A2` AAA
- `A3` AAA
```

And also try refreshing page sometime it will show up incorrectly like this:
Screenshot_227

#### What is current behaviour

After page loaded, sometimes embedding files are shown in wrong order.
Sometimes there are some files are not embedded. Have to refresh the page.

#### What is the expected behaviour

All files embedding in order correctly.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Browser version: Chrome latest version
- Docsify version: Latest
- Docsify plugins: None

### PR DESCRIPTION
**Pull request by tschaible**
**Summary**

fix #970 - updated the insertion of embedded tokens so it correctly handles embedded token results returning in any order

**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [X] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE

**Other information:**

The previous implementation incorrectly assumed that contents of embedded content would be returned in the order they were requested in the document.  This created unpredictable race conditions when multiple embeds were included.

I have run into this issue with embedded markdown, and have only attempted test-cases surrounding the markdown content specifically.

---

* [X ] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by tschaible** [comment]
When I initially opened this, 2 of the e2e test phases were marked as failed.

I was able to investigate this morning.  The only errors were timeouts in the before phases of the test suite.

I ran the e2e tests locally without issue and have re-pushed the change.  This time everything passed without issue.

I believe the original failure was simply an intermittent failure of the test framework setup.

I have also done some basic testing with Firefox and Safari, in addition to my additional tests in Chrome.  I am not planning further updates, at this time.  This change seems to effectively fix #970 in my use cases.

Please let me know if there is anything else I can do to assist in getting this merged.

**Comment by anikethsaha** [comment]
thanks for the PR and sorry for the delayed.
the tests are not so strong as of now, it bugs most of the time. 
I will try to review it soon .

**Comment by anikethsaha** [comment]
cc @docsifyjs/reviewers

**Comment by anikethsaha** [comment]
@Koooooo-7 can you `approved` the PR if its looks fine by you. I am in the process of adding 2 required approval before merging.

**Comment by erbridge** [comment]
This is affecting us, too. Any chance it could be merged?

File: src/core/render/embed.js [hunk 1]
```diff
@@ -117,17 +117,27 @@ export function prerenderEmbed({ compiler, raw = '', fetch }, done) {
     }
   });
 
-  let moveIndex = 0;
+  // keep track of which tokens have been embedded so far
+  // so that we know where to insert the embedded tokens as they
+  // are returned
+  const moves = [];
```
Comment (anikethsaha) [inline src/core/render/embed.js:123]:
```suggestion
  let moves = [];
```

Comment (tschaible) [reply src/core/render/embed.js:123]: Can I ask why you're recommending this change?  Is there a style guide or anything that you're using to recommend this?

The recommended change is counter to my understanding of `const`/`let` in Javascript.  `const` ensures that a variable cannot be reassigned, however, it does not prevent modification objects/arrays.

In the code, even though the `moves` array has values inserted into it, it is never re-assigned.  Usage of `const` in this case prevents any accidental re-assignment of `moves` that wasn't intended.

If there's a style guide I should be following, I'm happy to change it, but on the surface, the requested change seems confusing and could potentially lead to an error in the future.
