### PR TITLE
fix: handle hash navigation to prevent duplicate callbacks

### LINKED ISSUE #522: Always scroll to clicked sidebar content
Docsify does not scroll to the clicked sidebar link content if the link was the last sidebar link clicked.

1. Visit the [Markdown](https://jhildenbiddle.github.io/docsify-themeable/#/markdown) section on the [docsify-themeable](https://jhildenbiddle.github.io/docsify-themeable/) site
1. Click any section link (Ex: [Code](http://localhost:3000/#/markdown?id=code))
1. Scroll the page
1. Click the same section link

I believe the expectation is that docsify would scroll back to the section clicked. 

Perhaps removing the hash from the URL, then updating it with the section hash would provide a quick fix?

### PR DESCRIPTION
**Pull request by sy-records**
## Summary

This PR improves hash navigation handling by correctly setting the navigating flag even when the clicked link points to the current hash.

## Related issue, if any:

Close #522

## What kind of change does this PR introduce?

Bugfix

## For any code change,

- [x] Related documentation has been updated, if needed
- [x] Related tests have been added or updated, if needed

## Does this PR introduce a breaking change?

No

## Tested in the following browsers:

- [x] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Edge

### CODE REVIEW

File: src/core/router/history/hash.js [hunk 1]
```diff
@@ -46,7 +46,14 @@ export class HashHistory extends History {
       const el = e.target.tagName === 'A' ? e.target : e.target.parentNode;
 
       if (el && el.tagName === 'A' && !isExternal(el.href)) {
+        const hrefHash = new URL(el.href).hash;
+        const currentHash = location.hash;
```
Comment (Koooooo-7) [inline src/core/router/history/hash.js:50]: y not directly use `el.hash`?
