### PR TITLE
fix: Prevent initial unnecessary IntersectionObserver callback execution

### LINKED ISSUE #2504: On single page site Sidebar item highlight jumps back to top (first) Header (Docsify v5 Preview)
#### Steps to reproduce

1. View single page with Sidebar 
2. Tap on lower item, and view item on page
3. Scroll page back up

The highlighted item in the Sidebar jumps back to the first Header (item). Also, if the app name (i.e. Simple Docsify Templates) is clicked that jumps to the first Header item when the page reloads.

#### Current behaviour

The highlighted item in the Sidebar jumps back to the first Header (item)

#### Expected behaviour

As the page is scrolled up (or down), each item should highlight one by one as the page is scrolled back to the top (as is shown with Docsify v4, https://paulhibbitts.github.io/docsify-v4-single-page)

#### Other relevant information

- Docsify version:

Most recent (v5) Preview

- [X] Bug still occurs when all/other plugins are disabled?

- Docsify plugins (if the bug happens when plugins enabled, please try to isolate the issue):

- Your OS: Mac
- Node.js version:
- npm/yarn version:
- Browser version: Mac Chrome/Firefox/Safari

#### Please create a reproducible sandbox

Here is a demo using the most recent Preview:

https://paulhibbitts.github.io/docsify-v5-preview-single-page/#

To view bug, go to site, tap "Code" on Sidebar, and then scroll page back up. Might be related to #2509 

[Edit 307qqv236](https://codesandbox.io/s/307qqv236)

### LINKED ISSUE #2509: On single page site Sidebar does not highlight item navigated to (Docsify v5 Preview)
#### Steps to reproduce

View single page with Sidebar
Scroll down page, and tap on Header element
Copy resulting URL with id?
Open new Browser tab, paste copied URL

#### Current behaviour

The first item in the Sidebar remains highlighted

#### Expected behaviour

The item in the sidebar should be highlighted matching clicked id? on page (as is shown with Docsify v4, https://paulhibbitts.github.io/docsify-v4-single-page)

#### Other relevant information

- Docsify version:
- 
Most recent (v5) Preview

- [ ] Bug still occurs when all/other plugins are disabled?

- Docsify plugins (if the bug happens when plugins enabled, please try to isolate the issue):

#### Please create a reproducible sandbox

Here is a demo using the most recent Preview:

https://paulhibbitts.github.io/docsify-v5-preview-single-page/#

To view bug, go to site, scroll down page and click on a Header element, copy resulting URL, open new Browser tab and paste the URL Might be related to #2504 

[Edit 307qqv236](https://codesandbox.io/s/307qqv236)

### PR DESCRIPTION
**Pull request by sy-records**
## Summary

- Added a flag (`isInitialLoad`) to skip the first callback execution of the IntersectionObserver on page load.

## Related issue, if any:

Fix #2504
Fix #2509

## What kind of change does this PR introduce?

Bugfix

## For any code change,

- [x] Related documentation has been updated, if needed
- [x] Related tests have been added or updated, if needed

## Does this PR introduce a breaking change?

No

Yes
No

## Tested in the following browsers:

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by paulhibbitts — APPROVED** [review]
Thanks @sy-records , created Sandbox and tested (see issue comments) - all looks good to me!

File: src/core/event/index.js [hunk 1]
```diff
@@ -89,18 +95,21 @@ export function Events(Base) {
...
-                Array.from(headingsInView).sort((a, b) =>
-                  a.compareDocumentPosition(b) &
-                  Node.DOCUMENT_POSITION_FOLLOWING
-                    ? -1
-                    : 1,
-                )[0]
-              : // Get first and only item in set.
-                // May be undefined if no headings are in view.
-                headingsInView.values().next().value;
+          let activeHeading = undefined;
```
Comment (jhildenbiddle) [inline src/core/event/index.js:98]: Minor nitpick, but I think we can simplify this to:

```js
let activeHeading;
```

File: src/core/event/index.js [hunk 2]
```diff
@@ -89,18 +95,21 @@ export function Events(Base) {
             headingsInView[op](entry.target);
           }
 
-          const activeHeading =
-            headingsInView.size > 1
-              ? // Sort headings by proximity to viewport top and select first
```
Comment (jhildenbiddle) [inline src/core/event/index.js:94]: Let's retain these comments (moved to the appropriate place below).

File: src/core/event/index.js [hunk 3]
```diff
@@ -89,18 +95,21 @@ export function Events(Base) {
...
-                Array.from(headingsInView).sort((a, b) =>
-                  a.compareDocumentPosition(b) &
-                  Node.DOCUMENT_POSITION_FOLLOWING
-                    ? -1
-                    : 1,
-                )[0]
-              : // Get first and only item in set.
```
Comment (jhildenbiddle) [inline src/core/event/index.js:101]: Retain comment.

**Review by jhildenbiddle — CHANGES_REQUESTED** [review]
Looks good, @sy-records. A few minor nitpicks.

**Review by Koooooo-7 — COMMENTED** [review]
Shall we promote the `isInitialLoad` to the Object level as a field?
Then, we could reuse and keep consistence when any logic relies on the same `isInitialLoad ` lifecycle flag in future.

**Review by paulhibbitts — APPROVED** [review]
Thanks @sy-records and @jhildenbiddle , I've retested in the sandbox (with new Preview build) and things look good to me!

https://codesandbox.io/p/sandbox/docsify-v5-sidebar-fix-zwdm6p

**Review by jhildenbiddle — APPROVED** [review]
